services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: budgetplanner
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend: 
    container_name: springboot
    build:
      context: ./BudgetPlanner
      dockerfile: ../BudgetPlanner/backend.Dockerfile
    ports:
      - "2025:1430"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./BudgetPlanner-fr
      dockerfile: ../BudgetPlanner-fr/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: